env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - cmake
      - libc6-dev

# os:
#   - linux
#   - osx

language: node_js
node_js:
  - lts/*
  - node

script: 'npm run test-cover'
after_script: 'npm run report-cover'

after_failure: 'cat node_modules/mozjpeg-src/config.log'

notifications:
  email: false
