name: CI

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        node-version: [lts/*]

    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install autoconf and automake for macOS
        if: matrix.os == 'macos-latest'
        run: brew install autoconf automake

      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm build-native
      - run: pnpm test
